class Recipe {
  final int id;
  String name;
  String imageUrl;
  String time;
  String level;
  String portion;
  String description;
  List<String> ingredients;
  List<String> steps;

  Recipe(
      {required this.id,
      required this.name,
      required this.imageUrl,
      required this.time,
      required this.level,
      required this.portion,
      required this.description,
      required this.ingredients,
      required this.steps});
}

var recipeList = [
  Recipe(
    id: 1,
    name: 'Rendang',
    imageUrl:
        'https://lemang.sg/wp-content/uploads/2021/03/IMG_2536-1536x1024.jpg',
    time: '3 jam',
    level: 'Sulit',
    portion: '4 porsi',
    description:
        'Rendang adalah hidangan daging khas Indonesia yang dimasak dengan santan dan bumbu rempah kaya rasa.',
    ingredients: [
      '1 kg daging sapi (potong dadu)',
      '4 gelas santan',
      '2 batang serai (memarkan)',
      '5 lembar daun jeruk',
      '2 lembar daun kunyit (opsional)',
      '2 batang kayu manis',
      'Garam secukupnya',
      '2 sdm asam jawa',
      '3 sdm minyak goreng',
      'Bumbu halus:',
      '6 butir bawang merah',
      '5 siung bawang putih',
      '5 cabai merah',
      '3 cm jahe',
      '3 cm lengkuas',
      '2 sdt ketumbar bubuk',
      '1 sdt jinten bubuk',
      '1 sdt kunyit bubuk',
    ],
    steps: [
      'Haluskan semua bahan bumbu halus.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan daging sapi, aduk hingga daging tercampur bumbu.',
      'Tambahkan santan, serai, daun jeruk, daun kunyit, dan kayu manis.',
      'Masak hingga mendidih, lalu kecilkan api dan masak hingga daging empuk.',
      'Tambahkan garam dan asam jawa. Masak hingga rendang mengering dan berwarna gelap.',
      'Sajikan dengan nasi putih hangat.',
    ],
  ),
  Recipe(
    id: 2,
    name: 'Nasi Goreng',
    imageUrl:
        'https://poshjournal.com/wp-content/uploads/2019/08/nasi-goreng-recipe-indonesian-fried-rice-7-949x1024.jpg',
    time: '30 menit',
    level: 'Mudah',
    portion: '2 porsi',
    description:
        'Nasi goreng adalah hidangan populer Indonesia dengan nasi yang digoreng bersama bumbu.',
    ingredients: [
      '2 piring nasi putih',
      '2 butir telur',
      '3 sdm kecap manis',
      '2 siung bawang putih (cincang)',
      '2 butir bawang merah (iris)',
      '2 sdm minyak goreng',
      'Garam secukupnya',
      '1 sdt merica bubuk',
      '2 batang daun bawang (iris)',
      'Pelengkap: kerupuk dan acar',
    ],
    steps: [
      'Panaskan minyak, tumis bawang putih dan bawang merah hingga harum.',
      'Masukkan telur, orak-arik hingga matang.',
      'Tambahkan nasi, aduk rata dengan bumbu.',
      'Tuang kecap manis, tambahkan garam dan merica. Aduk hingga merata.',
      'Tambahkan daun bawang, masak sebentar, dan angkat.',
      'Sajikan dengan kerupuk dan acar.',
    ],
  ),
  Recipe(
    id: 3,
    name: 'Soto Ayam',
    imageUrl:
        'https://caramembuat.id/wp-content/uploads/2022/08/Cara-Membuat-Soto-Ayam-Bening.webp',
    time: '1 jam',
    level: 'Sedang',
    portion: '4 porsi',
    description:
        'Soto ayam adalah sup khas Indonesia dengan kuah kuning yang gurih.',
    ingredients: [
      '500 gram ayam',
      '1 liter air',
      '2 batang serai (memarkan)',
      '5 lembar daun jeruk',
      '2 cm lengkuas (memarkan)',
      '2 sdm minyak goreng',
      'Bumbu halus:',
      '5 siung bawang putih',
      '5 butir bawang merah',
      '3 cm kunyit',
      '2 cm jahe',
      '1 sdt ketumbar bubuk',
      'Garam dan merica secukupnya',
    ],
    steps: [
      'Rebus ayam hingga matang, angkat, suwir-suwir dagingnya.',
      'Panaskan minyak, tumis bumbu halus hingga harum.',
      'Masukkan serai, daun jeruk, dan lengkuas ke dalam tumisan.',
      'Tuang air rebusan ayam, masukkan ayam suwir.',
      'Masak hingga bumbu meresap, tambahkan garam dan merica.',
      'Sajikan soto dengan nasi, telur rebus, dan sambal.',
    ],
  ),
  Recipe(
    id: 4,
    name: 'Gado-Gado',
    imageUrl:
        'https://i0.wp.com/resepkoki.id/wp-content/uploads/2017/02/Resep-Gado-Gado.jpg?fit=500%2C479&ssl=1',
    time: '45 menit',
    level: 'Sedang',
    portion: '2 porsi',
    description: 'Gado-gado adalah salad khas Indonesia dengan saus kacang.',
    ingredients: [
      '200 gram tahu (goreng)',
      '200 gram tempe (goreng)',
      '100 gram tauge (seduh)',
      '100 gram kacang panjang (potong, rebus)',
      '2 kentang (rebus, potong)',
      '2 butir telur (rebus)',
      '100 gram selada',
      'Bumbu kacang:',
      '200 gram kacang tanah (goreng)',
      '3 siung bawang putih',
      '3 cabai merah',
      '3 sdm gula merah',
      '2 sdm air asam jawa',
      'Garam secukupnya',
      '200 ml air',
    ],
    steps: [
      'Haluskan bahan bumbu kacang.',
      'Tumis bumbu kacang dengan sedikit minyak hingga harum.',
      'Tambahkan air, masak hingga saus kacang mengental.',
      'Susun sayuran, tahu, tempe, dan telur di piring.',
      'Siram dengan saus kacang, sajikan.',
    ],
  ),
  Recipe(
    id: 5,
    name: 'Pecel Lele',
    imageUrl:
        'https://www.cookmeindonesian.com/wp-content/uploads/2021/03/pecel-lele1.jpg',
    time: '1 jam',
    level: 'Mudah',
    portion: '4 porsi',
    description:
        'Pecel lele adalah ikan lele goreng yang disajikan dengan sambal dan lalapan.',
    ingredients: [
      '4 ekor ikan lele',
      '3 siung bawang putih',
      '1 sdt garam',
      '1 sdt ketumbar',
      'Minyak untuk menggoreng',
      'Sambal:',
      '10 cabai rawit merah',
      '2 siung bawang putih',
      '2 butir tomat',
      '1 sdt terasi',
      '1 sdm gula merah',
      'Garam secukupnya',
    ],
    steps: [
      'Bersihkan ikan lele, lumuri dengan bawang putih, garam, dan ketumbar.',
      'Goreng ikan hingga matang dan renyah.',
      'Haluskan bahan sambal, lalu tumis hingga harum.',
      'Sajikan lele goreng dengan sambal dan lalapan.',
    ],
  ),
  Recipe(
    id: 6,
    name: 'Bakso',
    imageUrl:
        'https://i0.wp.com/arieskitchen.net/wp-content/uploads/2014/04/IMG_0414.jpg',
    time: '2 jam',
    level: 'Sedang',
    portion: '6 porsi',
    description:
        'Bakso adalah bola daging sapi kenyal yang disajikan dengan kuah kaldu.',
    ingredients: [
      '500 gram daging sapi giling',
      '50 gram tepung tapioka',
      '1 butir telur',
      '4 siung bawang putih (goreng)',
      'Garam dan lada secukupnya',
      'Kuah:',
      '2 liter air',
      '3 siung bawang putih (goreng, haluskan)',
      '1 batang daun bawang (iris)',
      'Garam dan lada secukupnya',
    ],
    steps: [
      'Campur daging sapi, tepung tapioka, bawang putih, garam, dan lada hingga kalis.',
      'Bentuk adonan menjadi bola kecil.',
      'Rebus bola bakso hingga mengapung, angkat.',
      'Masak kuah dengan bawang putih, garam, dan lada.',
      'Sajikan bakso dengan kuah panas.',
    ],
  ),
  Recipe(
    id: 7,
    name: 'Mie Ayam',
    imageUrl: 'https://icone-inc.org/wp-content/uploads/2015/09/Mie-Ayam3.jpg',
    time: '1 jam',
    level: 'Sedang',
    portion: '4 porsi',
    description:
        'Mie ayam adalah hidangan mie dengan ayam berbumbu kecap yang gurih.',
    ingredients: [
      '400 gram mie telur',
      '300 gram daging ayam (potong kecil)',
      '3 siung bawang putih',
      '2 sdm kecap manis',
      '2 sdm saus tiram',
      'Garam dan merica secukupnya',
      'Topping:',
      'Daun bawang dan bawang goreng',
    ],
    steps: [
      'Tumis bawang putih hingga harum, masukkan ayam.',
      'Tambahkan kecap manis, saus tiram, garam, dan merica.',
      'Rebus mie telur, tiriskan.',
      'Sajikan mie dengan ayam berbumbu dan topping.',
    ],
  ),
  Recipe(
    id: 8,
    name: 'Ayam Penyet',
    imageUrl:
        'https://singaporelocalfavourites.com/wp-content/uploads/2016/01/ayam-penyet-recipe-e1616040655377.jpg',
    time: '1 jam',
    level: 'Sedang',
    portion: '4 porsi',
    description:
        'Ayam penyet adalah ayam goreng yang dipenyet dengan sambal pedas khas Indonesia.',
    ingredients: [
      '4 potong ayam',
      '1 sdt garam',
      '1 sdt kunyit bubuk',
      '1 sdt ketumbar bubuk',
      'Minyak untuk menggoreng',
      'Sambal:',
      '10 cabai rawit merah',
      '2 siung bawang putih',
      '2 butir tomat',
      '1 sdt terasi',
      '1 sdm gula merah',
      'Garam secukupnya',
    ],
    steps: [
      'Lumuri ayam dengan garam, kunyit, dan ketumbar, diamkan 30 menit.',
      'Goreng ayam hingga matang dan berwarna kecokelatan.',
      'Haluskan bahan sambal, tumis hingga harum.',
      'Penyet ayam di atas sambal, sajikan dengan nasi dan lalapan.',
    ],
  ),
  Recipe(
    id: 9,
    name: 'Sate Ayam',
    imageUrl:
        'https://www.rumahmesin.com/wp-content/uploads/2017/03/resep-sate-ayam-madura-mencicipi-makanan-asli-indonesia-yang-mendunia.jpg.webp',
    time: '1 jam 30 menit',
    level: 'Sedang',
    portion: '6 porsi',
    description:
        'Sate ayam adalah hidangan daging ayam yang ditusuk dan dipanggang dengan bumbu kacang.',
    ingredients: [
      '500 gram daging ayam (potong kecil)',
      '20 tusuk sate',
      'Bumbu marinasi:',
      '2 siung bawang putih (haluskan)',
      '3 sdm kecap manis',
      '1 sdt ketumbar bubuk',
      '1 sdt garam',
      'Bumbu kacang:',
      '200 gram kacang tanah (goreng)',
      '2 siung bawang putih',
      '3 cabai merah',
      '3 sdm gula merah',
      '200 ml air',
      '1 sdm air asam jawa',
      'Garam secukupnya',
    ],
    steps: [
      'Rendam potongan ayam dengan bumbu marinasi selama 30 menit.',
      'Tusukkan ayam ke tusuk sate.',
      'Haluskan bahan bumbu kacang, masak hingga mengental.',
      'Panggang sate hingga matang, olesi dengan kecap manis.',
      'Sajikan sate dengan bumbu kacang dan lontong.',
    ],
  ),
  Recipe(
    id: 10,
    name: 'Gudeg',
    imageUrl:
        'https://static.promediateknologi.id/crop/0x0%3A0x0/750x500/webp/photo/2023/08/03/gudeg-jogja-3289501399.jpg',
    time: '4 jam',
    level: 'Sulit',
    portion: '6 porsi',
    description:
        'Gudeg adalah makanan khas Yogyakarta yang berbahan dasar nangka muda dengan rasa manis.',
    ingredients: [
      '1 kg nangka muda (potong kecil)',
      '1 liter santan',
      '5 lembar daun salam',
      '3 cm lengkuas (memarkan)',
      '200 gram gula merah',
      '5 butir telur (rebus)',
      'Bumbu halus:',
      '5 siung bawang putih',
      '5 butir bawang merah',
      '3 butir kemiri',
      '1 sdt ketumbar bubuk',
      'Garam secukupnya',
    ],
    steps: [
      'Rebus nangka muda bersama daun salam dan lengkuas hingga setengah matang.',
      'Haluskan bumbu, tumis hingga harum.',
      'Masukkan bumbu ke rebusan nangka, tambahkan santan, gula merah, dan garam.',
      'Masak dengan api kecil hingga nangka empuk dan kuah mengental.',
      'Tambahkan telur rebus, masak sebentar, sajikan.',
    ],
  ),
];
